apiVersion: v1
kind: Service
metadata:
  name: java
  labels:
    app: java
    group: certificate-example
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 8443
      name: https
  selector:
    app: java
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java
  labels:
    app: java
    group: certificate-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
        - name: java
          image: voor/java-service:latest
          env:
            - name: SERVER_SSL_KEYSTORETYPE
              value: "PKCS12"
            - name: SERVER_SSL_KEYSTORE
              value: "/etc/keystore/keystore.p12"
            - name: SERVER_SSL_KEYSTOREPASSWORD
              valueFrom:
                secretKeyRef:
                  name: java-keystore
                  key: password
            - name: SERVER_SSL_KEYALIAS
              valueFrom:
                secretKeyRef:
                  name: java-keystore
                  key: alias
            - name: SERVER_PORT
              value: "8443"
            - name: OTHER_SERVER_HOST
              value: "nodejs.default.svc.cluster.local"
            - name: OTHER_SERVER_PORT
              value: "443"
          ports:
            - name: http
              containerPort: 8443
              protocol: TCP
          volumeMounts:
            - name: java-keystore
              mountPath: "/etc/keystore"
              readOnly: true
            - name: java-truststore
              mountPath: "/etc/ssl/certs/java"
              readOnly: true
      volumes:
        - name: java-keystore
          secret:
            secretName: java-keystore
        - name: java-truststore
          secret:
            secretName: java-truststore
